### ISSUE TITLE
[Net2] GetLocalIPs silently fails on Windows

### ISSUE THREAD

**Issue by ryanskidmore** [dropbox/godropbox#120]
When net2.GetLocalIPs is called on a Windows (amd64 only platform tested currently) machine, the call silently fails without providing any LocalIPs nor an error.

**Comment by jamwt** [comment]
Interesting; have you used other parts of the library successfully on windows?  Windows support was never really a goal of the project, and it would surprise me if this was our only issue.

**Comment by ryanskidmore** [comment]
I've not tested unfortunately, I think the issue may be with Go itself - since I can't see anything that would cause it to fail on the library's part. This doesn't surprise me though, since there's no built in way on Windows to find the external IP address.

**Comment by jamwt** [comment]
Thanks for the report; we've updated the README etc to make this explicit, but this repo is definitely only safe for use on Linux systems right now.  We really haven't made any effort at portability yet, and we're only using this in depth on 64-bit linux systems at Dropbox.  So the library is platform specific for now.
