### ISSUE TITLE
Incorrect synchronization pattern in singleton.go

### ISSUE THREAD

**Issue by pavadeli** [dropbox/godropbox#129]
The file *godropbox/singleton/singleton.go* contains an incorrect synchronization pattern. It is assumed that `s.data` will always be filled correctly when `s.initialized == true`, but this is a false assumption. For more information, see the section on **Incorrect synchronization** at https://golang.org/ref/mem.

Either document that the `Get()` method might (theoretically) return garbage :grimacing: or use the sync/atomic package. For inspiration look at `sync.Once` (http://golang.org/src/sync/once.go?s=1139:1166#L25). :smile:

**Comment by PatrickDropbox** [comment]
Thanks for pointing this out!  I've send out a fix #130.
