### ISSUE TITLE
Memcache Library has no default connect timeout

### ISSUE THREAD

**Issue by zviadm** [dropbox/godropbox#154]
It defaults to using net.Dial instead of using DialTimeout with some sensible timeout like 1 second by default.
Should we change the default? or should we just change everywhere we use it?

@PatrickDropbox @rajatgoel

**Comment by zviadm** [comment]
It is also unfortunate 'net2.ConnectionOptions' is publicly available struct instead of it being private and having something like DefaultConnectionOptions() function which is publicly available

**Comment by PatrickDropbox** [comment]
sorry, missed your message (didn't get a github notification ...).  The Dial function is pass in by the user of the memory library, in this case, us.  I agree that we need to fix this in house.

I also agree that DefaultConnectionOptions() is a nice to have.  Will look into that.
