### ISSUE TITLE
resource pool Close func may not be called

### ISSUE THREAD

**Issue by Cas-pian** [dropbox/godropbox#209]
Hi, guys!  
There might be a bug, which seem to be ingore some resource without calling Close function in SimpleResourcePool.getIdleHandle
```
	if len(p.idleHandles) > 0 {
		p.idleHandles = []*idleHandle{}
	}
```
If goes here, it means there's no handle can be used, but why don't close them, just ingore?
I think it might be this:  
```
	if len(p.idleHandles) > 0 {
		toClose = p.idleHandles
		p.idleHandles = []*idleHandle{}
	}
```
Thanks!

**Comment by pattyshack** [comment]
I don't think this is an issue.  if the program have reached this condition, then i must be greater or equal to len(p.idleHandles) because of the condition immediately above this.  i is transitively greater than 0 because of this conditional block.  hence toClose is set correctly 2 conditions above.

Is there some flaw in my reasoning?

**Comment by pattyshack** [comment]
o, ic. there's an off by one error.  thanks for pointing this out.  I'll send out a fix

**Comment by pattyshack** [comment]
Thanks for pointing out the error

**Comment by Cas-pian** [comment]
Hmm, Thanks for your reply!   
But I  just seems found it' not ok in your patch, seems in the normal case the handle is included in closeHandle and will be closed, because when 'break' is executed i points to the right handle.

**Comment by Cas-pian** [comment]
Please ignore my last comment, I misunderstand it.
Thanks!

**Comment by Genisekeyandrandle** [comment]
[LLC Operating Agreement.pdf](https://github.com/dropbox/godropbox/files/709393/LLC.Operating.Agreement.pdf)

**Comment by Genisekeyandrandle** [comment]
Redskingiftshop2.com we are on your side until th end of time
![expresslogo_40](https://cloud.githubusercontent.com/assets/23660073/21998964/5347d078-dbfd-11e6-8247-aaa1d4197e83.gif)
