### ISSUE TITLE
Per-request memcache client timeouts

### ISSUE THREAD

**Issue by benkaras** [dropbox/godropbox#244]
Would you be open to a pull-request adding support for customizing the timeouts on individual memcache requests?  For example, 10ms for Get() and 100ms for a later Get(). 

Since this is a larger change, I wanted to check with you first before digging into this.

**Rough Proposal:**
Pass deadline using context.Context. To keep API compatibility, introduce new interfaces for this purpose: ContextClient, ContextClientShard, ContextManagedConn etc. Have existing implementations pass context.Background() to the new methods. It should be possible to leave the existing API unchanged.

Please let me know if you'd be open to such a change, or if there's a different approach you'd prefer me to take here.

Thanks in advance,
Ben Karas
Google

**Comment by to75988070** [comment]
Leave

**Comment by benkaras** [comment]
Hi Shailesh,

Thank you for checking! I have a change about 95% done to implement this.
It's fairly extensive since it adds interfaces that take context.Context as
the 1st param. Do you want to help review it when it's ready?

-Ben

**Comment by ShaileshSurya** [comment]
Hi @benkaras, 

Yes, I would love to do that. Please do mention to me once it is ready.

**Comment by orborde** [comment]
This sure doesn't look like it's gonna happen. Feel free to reopen if I've guessed wrongly!
